### ISSUE TITLE
Add a command to download Hermes profile

### ISSUE THREAD

**Issue by jessieAnhNguyen** [MLH-Fellowship/cli#1]
### Add a command that pulls the latest Hermes profile from the Android device to the local machine
Proposals: 
- [x] `react-native profile-hermes dstfilepath`: pull the latest profile generated by the Android device to the local machine
- [x] `react-native profile-hermes dstfilepath --filename [string]`: pull a specific profile generated by the Android device to the local machine

**Comment by saphal1998** [comment]
Using ```childprocess``` to simulate ```adb shell run-as com.packagename```

- [x] Look through [documentation](https://nodejs.org/api/child_process.html) and [existing implementations](http://www.google.com)
- [x] Parse stdout to get filenames (list out the files)
- [x] Using ```pipe``` (for streamed data) or ```scp```  (for copying files). Dependent on file-size. Look into which works better for us, (probably look into commands that pull files from the device, and follow the same method to get profiles) => basically to pull the file

**Comment by jessieAnhNguyen** [comment]
Managed to run commands ```adb pull``` and ```adb shell run-as``` on a separate test project. Will integrate that into the CLI codebase.

**Comment by jessieAnhNguyen** [comment]
Enhancement: get the ```packageName``` from the RN directory
- [x] Parse it from the react native codebase
